apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloflaskgit
spec:
  selector:
    matchLabels:
      app: helloflaskgit
  template:
    metadata:
      labels:
        app: helloflaskgit
    spec:
      containers:
      - name: helloflaskgit
        image: ririfiras/helloflaskgit:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_APP
            value: app.py
          - name: WEB2_COUNTER_MSG
            value: visitors on argo app deployment
---
apiVersion: v1
kind: Service
metadata:
  name: helloflaskgit
spec:
  selector:
    app: helloflaskgit
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
